[View in Colaboratory](https://colab.research.google.com/github/guitar79/OA-2018/blob/master/getting_start_python.ipynb)

# Python Basics

python 사용법에 대해 간단히 설명한다. 자세한 내용은 official Python tutorial (https://docs.python.org/3/tutorial/index.html) 을 참고하기 바란다.



python package를 사용하기 위해서는 미리 설치되어 있어야 한다. pip 또는 anaconda 를 이용하여 설치할 수 있는데, anaconda (https://www.anaconda.com/download/) 를 주로 사용할 것이다. 


**Importing**

이름이 'numpy'인 Package는 아래와 같이 불러올 수 있다. 

In [0]:
import numpy

'astropy'라는 package의 여러 'subpackage' 중에서 이름이 'constants'인 subpackage 만을 불러올 경우에는 아래와 같이 입력한다.

In [0]:
from astropy import constants

'fits' 라는 이름의 subsub package 가 있는 경우, 즉 ssub ∈ sub ∈ pkg 인 경우에는 아래와 같이 불러올 수 있다. 


In [0]:
from astropy.io import fits

'matplotlib'라는 이름의 package에 'pyplot' 함수를 'plt'라는 이름으로 사용하고자 한다면 다음과 같이 입력해 준다.

In [0]:
import matplotlib.pyplot as plt

 (larger).(smaller).(even_smaller)와 같은 형식으로 패키지를 사용할 수 있다.
 'astropy.stats'라는 이름의 package (module) 안에 있는 'sigma_clip'이라는 함수를 사용하고자 한다면 다음과 같이 입력해 준다.



In [0]:
astropy.stats.sigma_clip()

**Data Types**

Python도 다른 프로그래밍 언어처럼 몇몇 데이터 타입이 있다. 그리고 데이터 타입을 보려면 다음과 같이 type 함수를 사용할 수 있다.

In [0]:
a = 3     # integer
b = 3.14  # float (real number)
c = 'cc'  # string

print(a)  # will print 3
print(b)  # will print 3.14
print(c)  # will print cc
print(type(a))   # the data types of a, b, c
print(type(b))
print(type(c))

3
3.14
cc
<class 'int'>
<class 'float'>
<class 'str'>


물론 'True', 'False' 형태도 있다. 

In [0]:
print(type(True))
print(type(False))

<class 'bool'>
<class 'bool'>


'index'는 '0' 부터 시작하며, 다음과 같은 데이터 형태들이 있다. 

In [0]:
import numpy as np

A = [0,1,2]            # classical Python "list"
B = (0,1,2)            # classical Python "tuple"
C = np.array((0,1,2))  # numpy n-dimensional array
print('A: ', A[0], A[1], A[2])
print('B: ', B[0], B[1], B[2])
print('C: ', C[0], C[1], C[2])
print('ABC: ', A, B, C)
print('type: ', type(A), type(B), type(C))

A:  0 1 2
B:  0 1 2
C:  0 1 2
ABC:  [0, 1, 2] (0, 1, 2) [0 1 2]
type:  <class 'list'> <class 'tuple'> <class 'numpy.ndarray'>


In [0]:
C_obj = np.array([0,1,'test'], dtype='object')
print(C_obj)
print(C_obj[0], C_obj[1], C_obj[2])
print(type(C_obj[0]), type(C_obj[1]), type(C_obj[2]))

[0 1 'test']
0 1 test
<class 'int'> <class 'int'> <class 'str'>


**Conditions/Loops**

In [0]:
x, y, z = 3, 3.14, 10-7
if (x != y):
    print('Different!')


Different!


In [0]:
L  = np.arange(0, 10, 1) # numpy array with elements [0, 10] with interval 1
L1 = np.ones((10))  # 10 by 1 sized numpy array, filled with 1

for i in range(0,10):
    if (L[i] == 9):
        print("\t'Oh it's NEIN!'")
        continue
    print(L[i], end=' ') # option "end" sets the ending part for each print; test many cases by yourself!
    print(L[i]==L1[i], end=' ')

In [0]:
L1 = np.ones((10))  # 10 by 1 sized numpy array, filled with 1
j = 0
while (1):  # identical to while(True)
    print(j, L1[j])
    j += 1
    if(j==5):
        print("j reached 5")
        break

** Numpy**

In [0]:
num1 = np.arange(0, 11, 2) # generate numpy array [0, 11) with interval 2
num2 = np.random.rand(6) # generate six random numbers (0,1)

# Basics
print("num1:")
print(num1)
print("num2:")
print(num2)
print("\nnum1^2:") # "\n" means "new line".
print(num1**2)           # Square each element
print("\nnum1^(0.5):")
print(np.sqrt(num1))     # Square root of each element
print("\nnum1 in 2 x 3 form:")
print(num1.reshape(2,3)) # reshape the num1 into 2 by 3 form. 
# Identical to np.reshape(num1, (2,3))
num3 = np.reshape(num1, (2,3))
print("\nnum3's row 0:")
print(num3[0,:])         # row 0, column all (:)
print("\nnum3's min/max:")
print(num3.min(), num3.max())
# Identical to np.min(num3), np.max(num3)
print(np.where(num3 == num3.max())) # Show at which position the maximum occurs

# MASKING
tf   = np.array([False, True, False, True, True, False])
print("\nnum1's selected elements:")
print(num1[tf])

tf   = (num2*10 > 3)       # Select only elements larger than 3 from num2*10
# RHS is identical to just "num2*10>3"
print("\nnum2's selected elements:")
print(num2[tf])

num1:
[ 0  2  4  6  8 10]
num2:
[0.56211736 0.99961462 0.48370879 0.53373763 0.35954605 0.74961354]

num1^2:
[  0   4  16  36  64 100]

num1^(0.5):
[0.         1.41421356 2.         2.44948974 2.82842712 3.16227766]

num1 in 2 x 3 form:
[[ 0  2  4]
 [ 6  8 10]]

num3's row 0:
[0 2 4]

num3's min/max:
0 10
(array([1]), array([2]))

num1's selected elements:
[2 6 8]

num2's selected elements:
[0.56211736 0.99961462 0.48370879 0.53373763 0.35954605 0.74961354]
